name: build

on:
  workflow_call:
    inputs:
      operating_system:
        description: 'OS'
        required: true
        default: 'ubuntu-latest'
        type: string
      architecture:
        description: 'Architecture'
        required: true
        default: 'X64'
        type: string

jobs:
  build:
    runs-on: ${{ inputs.operating_system }}
    steps:
      - name: Install Protobuf
        # Run `git checkout`
        uses: actions/checkout@v2
        # Install the `buf` CLI
        uses: bufbuild/buf-setup-action@v1.29.0
      - name: Install Protoc
        uses: arduino/setup-protoc@v1
          with:
            version: '3.x'
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build
        run: cargo build --release
      - name: Upload the binary artifacts
        uses: actions/upload-artifact@v3
        with:
          name: ${{ runner.os }}-${{ runner.arch }}
          path: target/release/valve
          retention-days: 5