name: build

on:
  workflow_call:
    inputs:
      operating_system:
        description: 'OS'
        required: true
        type: string
      architecture:
        description: 'Architecture'
        required: true
        type: string

jobs:
  build:
    runs-on: ${{ inputs.operating_system }}, ${{ inputs.architecture }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Protobuf
        uses: bufbuild/buf-setup-action@v1.29.0
      - name: Install Protoc
        uses: arduino/setup-protoc@v1
        with:
          version: '3.x'
      - name: Build
        run: cargo build --release
      
      - name: Upload the binary artifacts
        if: ${{ runner.os != 'Windows' }}
        uses: actions/upload-artifact@v3
        with:
          name: ${{ runner.os }}-${{ runner.arch }}
          path: target/release/valve
          retention-days: 5

      - name: Upload the binary artifacts
        if: ${{ runner.os == 'Windows' }}
        uses: actions/upload-artifact@v3
        with:
          name: ${{ runner.os }}-${{ runner.arch }}
          path: target/release/valve.exe
          retention-days: 5