name: build

on:
  workflow_call:
    inputs:
      operating_system:
        description: 'OS'
        required: true
        default: 'ubuntu-latest'
        type: string
      architecture:
        description: 'Architecture'
        required: true
        default: 'X64'
        type: string

jobs:
  build:
    runs-on: ${{ inputs.operating_system }}
    steps:
      - uses: actions/checkout@v2
      - uses: wizhi/setup-buf@v1
        with:
          version: '0.36.0'
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build
        run: cargo build --release