name: build

on:
  workflow_call:
    inputs:
      operating_system:
        description: 'OS'
        required: true
        default: 'ubuntu-latest'
      architecture:
        description: 'Architecture'
        required: true
        default: 'X64'

jobs:
  build:
    runs-on: ${{ inputs.operating_system }}
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Build
      run: cargo build --release