name: Create CuraPackage

on:
  workflow_dispatch:

jobs:
  linux-modern-installer:
    uses: ./.github/workflows/build.yml
    with:
      architecture: X64
      operating_system: ubuntu-22.04
    secrets: inherit

  macos-installer:
    uses: ./.github/workflows/build.yml
    with:
      architecture: X64
      operating_system: macos-11.0
    secrets: inherit

  create-curapackages:
    runs-on: "ubuntu-latest"
    needs: [ linux-modern-installer, macos-installer]

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Download linux modern binary artifacts
        uses: actions/download-artifact@v2
        with:
          name: Linux-X64
          path: valve/x86_64/Linux

      - name: Download mac x64 binary artifacts
        uses: actions/download-artifact@v2
        with:
          name: macOS-X64
          path: valve/x86_64/Darwin

      - name: Download mac arm binaries artifacts
        uses: actions/download-artifact@v2
        with:
          name: macOS-ARM64
          path: valve/arm64/Darwin

      - name: Download win X64 binaries artifacts
        uses: actions/download-artifact@v2
        with:
          name: Windows-X64
          path: valve/x86_64/Windows

      - name: Upload the Cura plugin source
        uses: actions/upload-artifact@v3
        with:
          name: cura-plugin
          path: |
            valve/**/*
          retention-days: 5

      - uses: fieldOfView/cura-plugin-packager-action@main
        with:
          source_folder: "cura-plugin/CuraEngineGradualFlow"
          package_info_path: "cura-plugin/CuraEngineGradualFlow/package.json"

      - name: Upload the Cura package
        uses: actions/upload-artifact@v3
        with:
          name: cura-package
          path: |
            *.curapackage
          retention-days: 5